// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBkaII1FoNVrgqInUVm8gl1nS90QrAVvQ',
    appId: '1:519170408267:web:c40a09978626ec930272ce',
    messagingSenderId: '519170408267',
    projectId: 'invoice-e33ed',
    authDomain: 'invoice-e33ed.firebaseapp.com',
    storageBucket: 'invoice-e33ed.appspot.com',
    measurementId: 'G-LBB6K39ZFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqndU8Yjxb4CSNtcvz1DyK38cQI6iqaJ8',
    appId: '1:519170408267:android:1a70158ae1c207050272ce',
    messagingSenderId: '519170408267',
    projectId: 'invoice-e33ed',
    storageBucket: 'invoice-e33ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRlrlKoOhDOkArIDWJiqBg0UbtHhiBPew',
    appId: '1:519170408267:ios:0babe110040d78190272ce',
    messagingSenderId: '519170408267',
    projectId: 'invoice-e33ed',
    storageBucket: 'invoice-e33ed.appspot.com',
    iosClientId: '519170408267-5sb60bd89gav3upel0tg6slol9c0aqjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRlrlKoOhDOkArIDWJiqBg0UbtHhiBPew',
    appId: '1:519170408267:ios:e1c5dca0ef0f0e590272ce',
    messagingSenderId: '519170408267',
    projectId: 'invoice-e33ed',
    storageBucket: 'invoice-e33ed.appspot.com',
    iosClientId: '519170408267-eol0650ksv55ve35a03oi6129pdutc6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
